// Generated by LiveScript 1.5.0
/**
 * @package   WebTorrent DHT
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2017, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  var browserify, del, gulp, rename, tap, uglifyEs, uglify, DESTINATION, gutil;
  browserify = require('browserify');
  del = require('del');
  gulp = require('gulp');
  rename = require('gulp-rename');
  tap = require('gulp-tap');
  uglifyEs = require('uglify-es');
  uglify = require('gulp-uglify/composer')(uglifyEs, console);
  DESTINATION = 'dist';
  gutil = require('gulp-util');
  gulp.task('build', ['clean', 'browserify', 'minify']).task('browserify', ['clean'], function(){
    return gulp.src('webtorrent-dht.js', {
      read: false
    }).pipe(tap(function(file){
      file.contents = browserify({
        entries: file.path,
        standalone: 'webtorrent_dht'
      }).bundle();
    })).pipe(rename({
      suffix: '.browser'
    })).pipe(gulp.dest(DESTINATION));
  }).task('clean', function(){
    return del(DESTINATION);
  }).task('minify', ['browserify'], function(){
    return gulp.src(DESTINATION + "/*.js").pipe(uglify()).on('error', function(err){
      gutil.log(gutil.colors.red('[Error]'), err.toString());
    }).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest(DESTINATION));
  });
}).call(this);
