// Generated by LiveScript 1.5.0
/**
 * @package WebTorrent DHT
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var bittorrentDht, inherits, kRpcWebrtc, noop, x$;
  bittorrentDht = require('bittorrent-dht');
  inherits = require('inherits');
  kRpcWebrtc = require('./k-rpc-webrtc');
  module.exports = webtorrentDht;
  noop = function(){};
  /**
   * k-rpc modified to work with WebRTC
   *
   * @constructor
   */
  function webtorrentDht(options){
    options == null && (options = {});
    if (!(this instanceof webtorrentDht)) {
      return new webtorrentDht(options);
    }
    options = Object.assign({}, options);
    if (options.hash) {
      options.idLength = options.hash(Buffer.from('')).length;
    }
    options.krpc = options.krpc || kRpcWebrtc(options);
    bittorrentDht.call(this, options);
  }
  inherits(noop, bittorrentDht);
  inherits(webtorrentDht, noop);
  x$ = webtorrentDht.prototype;
  x$.listen = function(port, address, callback){
    port == null && (port = 16881);
    address == null && (address = '127.0.0.1');
    this._rpc.bind(port, address, callback);
  };
  x$.toJSON = function(){
    return {
      nodes: this._rpc.socket.socket.known_ws_servers(),
      values: bittorrentDht.prototype.toJSON.call(this).values
    };
  };
}).call(this);
