// Generated by LiveScript 1.5.0
/**
 * @package   WebTorrent DHT
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2017, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  window.dht = new webtorrent_dht({
    k: 3,
    nodes: [{
      host: '127.0.0.1',
      port: 16881
    }],
    simple_peer_opts: {
      config: {
        iceServers: []
      }
    }
  });
}).call(this);
