// Generated by LiveScript 1.5.0
/**
 * @package   WebTorrent DHT
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2017, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  var DHT;
  DHT = require('../webtorrent-dht');
  global.dht = new DHT({
    k: 3,
    nodes: [],
    simple_peer_opts: {
      config: {
        iceServers: []
      }
    }
  });
  dht.listen(16881, '127.0.0.1', function(){
    console.log('now listening');
  });
}).call(this);
