// Generated by LiveScript 1.5.0
/**
 * @package WebTorrent DHT
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var DHT;
  DHT = require('../webtorrent-dht');
  global.dht = new DHT({
    nodes: [{
      host: '127.0.0.1',
      port: 16881
    }],
    simple_peer_opts: {
      config: {
        iceServers: []
      }
    }
  });
}).call(this);
